"""response recommendations

Revision ID: 0f8ef0cf8739
Revises: 58f50f8376bf
Create Date: 2026-07-03 02:13:49.308183

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8ef0cf8739'
down_revision: str | None = '58f50f8376bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_recommendations_action_type'), 'response_recommendations', ['action_type'], unique=False)
    op.create_index(op.f('ix_response_recommendations_id'), 'response_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_response_recommendations_severity'), 'response_recommendations', ['severity'], unique=False)
    op.create_index(op.f('ix_response_recommendations_source_id'), 'response_recommendations', ['source_id'], unique=False)
    op.create_index(op.f('ix_response_recommendations_source_type'), 'response_recommendations', ['source_type'], unique=False)
    op.create_index(op.f('ix_response_recommendations_status'), 'response_recommendations', ['status'], unique=False)
    op.create_table('response_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['response_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_audit_event'), 'response_audit', ['event'], unique=False)
    op.create_index(op.f('ix_response_audit_id'), 'response_audit', ['id'], unique=False)
    op.create_index(op.f('ix_response_audit_recommendation_id'), 'response_audit', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_audit_recommendation_id'), table_name='response_audit')
    op.drop_index(op.f('ix_response_audit_id'), table_name='response_audit')
    op.drop_index(op.f('ix_response_audit_event'), table_name='response_audit')
    op.drop_table('response_audit')
    op.drop_index(op.f('ix_response_recommendations_status'), table_name='response_recommendations')
    op.drop_index(op.f('ix_response_recommendations_source_type'), table_name='response_recommendations')
    op.drop_index(op.f('ix_response_recommendations_source_id'), table_name='response_recommendations')
    op.drop_index(op.f('ix_response_recommendations_severity'), table_name='response_recommendations')
    op.drop_index(op.f('ix_response_recommendations_id'), table_name='response_recommendations')
    op.drop_index(op.f('ix_response_recommendations_action_type'), table_name='response_recommendations')
    op.drop_table('response_recommendations')
    # ### end Alembic commands ###
